inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Airbnb/RiskyActiverecordInvocation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Naming/VariableName:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false