version: '3'

services:
    app:
        build: .
        command: bundle exec puma -C config/puma.rb -e production
        #  command: bundle exec puma -C config/puma.rb
        volumes:
            - .:/child_app
            - public-data:/child_app/public
            - tmp-data:/child_app/tmp
            - log-data:/child_app/log
        tty: true
        #  depends_on:
        #      - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: child_app_db
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "4306:3306"
    #  db:
    #      image: mysql:5.7
    #      environment:
    #          MYSQL_ROOT_PASSWORD: password
    #          MYSQL_USER: user
    #          MYSQL_PASSWORD: 1234
    #          MYSQL_DATABASE: child_app_db
    #      volumes:
    #          - db-data:/var/lib/mysql
    #      ports:
    #          - "4306:3306"

    web:
        build:
            context: containers/nginx
        volumes:
            - public-data:/child_app/public
            - tmp-data:/child_app/tmp
        ports:
            - 80:80
        depends_on:
            - db
        
volumes:
  gem_data:
  public-data:
  tmp-data:
  log-data:
  db-data: