version: '3'

services:
    app:
        build:
            context: .
        env_file:
            - ./environments/db.env
        command: bundle exec puma -C config/puma.rb
        volumes:
            - .:/webapp
            - public-data:/myapp/public
            - tmp-data:/myapp/tmp
            - log-data:/myapp/log
        depends_on:
            - db
    db:
        image: mysql:5.7
        env_file:
            - ./environments/db.env
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql/volumes:/var/lib/mysql

    web:
        build:
            context: containers/nginx
        volumes:
            - public-data:/myapp/public
            - tmp-data:/myapp/tmp
        ports:
            - 80:80
        depends_on:
            - app
        
volumes:
  gem_data:
  public-data:
  tmp-data:
  log-data:
  db-data: