# MySQL. Versions 5.1.10 and up are supported.
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db

development:
  <<: *default
  database: child_app_development

test:
  <<: *default
  database: child_app_test

production:
  <<: *default
  database: child_app_production
  username: child_app
  password: <%= ENV['Child_APP_DATABASE_PASSWORD'] %>
